include gains workshop initial page
iiasa/ece-teaching pull request #19
Opened 2021-09-09 08:03 UTC by robert4gains

GAINS workshop to index
GAINS workshop initial page

2021-09-09 10:10 UTC, danielhuppmann requested changes
Thanks @robert4gains - a few suggestions inline, then good to go!

2021-09-09 10:10 UTC, danielhuppmann commented on gains_workshops.rst
> +^^^^^^^^^^^^^^^^^^
Not strictly necessary, but better to keep the title and the syntax-highlighting in sync
```suggestion
^^^^^^^^^^^^^^^
```

2021-09-09 10:10 UTC, danielhuppmann commented on gains_workshops.rst
> +GAINS Capacity building
Not quite what this line does? Is this meant as a heading? If yes, please add syntax highlighting

2021-09-09 10:10 UTC, danielhuppmann commented on gains_workshops.rst
> +constraints and run analysis on costs and co - benefit.
Minor editorial suggestion
```suggestion
constraints and run analysis on costs and co-benefits.
```

2021-09-09 10:10 UTC, danielhuppmann commented on index.rst
> +
No need to add extra lines here...

2021-09-09 11:48 UTC, robert4gains commented
All recommended changes done

2021-09-10 14:58 UTC, danielhuppmann approved these changes
Looks good to me as a first step towards including GAINS in the ECE teaching pages!
Over to @LauWien for a final review and merge.

2021-09-13 08:05 UTC, LauWien requested changes
Thank you! Looks good to me. I would just delete the two additional lines 47 and 48 in the _index.rst_ file as suggested.

2021-09-13 08:05 UTC, LauWien commented on index.rst
> +
```suggestion
```

2021-09-13 08:05 UTC, LauWien commented on index.rst
> +
```suggestion
```

2021-09-13 08:17 UTC, LauWien approved these changes

2021-09-13 08:19 UTC, merged